name: Deploy Simple Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install backend dependencies
      working-directory: ./backend/**
      run: npm install

    - name: Install frontend dependencies
      working-directory: ./frontend/**
      run: npm install

    - name: Build frontend
      working-directory: ./frontend/**
      run: npm run build

    - name: Deploy (Example Placeholder)
      run: echo "Deploy to your hosting service here."
