name: Deploy Simple Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install

    - name: Build frontend
      working-directory: ./backend
      run: npm run build
      
    - name: Start backend server
      working-directory: ./backend
      run: npm start &

      
    # - name: Wait for server to start
    #   run: |
    #     sleep 10
    #     curl -f http://localhost:28080 || exit 1

    - name: Deploy
      run: echo "Deploy to your hosting service here."
